org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# IDs de prueba de Google. Sustituir por los de tu cuenta AdMob antes de Play Store.
ADMOB_APP_ID=ca-app-pub-3940256099942544~3347511713
ADMOB_BANNER_UNIT_ID=ca-app-pub-3940256099942544/9214589741
